name: Laravel Setup and Package Install

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer Dependencies
      run: |
        composer install --no-interaction --prefer-dist

    - name: Install Laravel
      run: |
        composer create-project laravel/laravel temp-laravel --prefer-dist

    - name: Navigate to Temporary Laravel App Directory
      run: |
        cd temp-laravel

    - name: Install mehedi8gb/api-crudify Package
      run: |
        cd ..  # Navigate back to the repository root
        composer require mehedi8gb/api-crudify --dev

    - name: Run Laravel Tests
      run: |
        cd temp-laravel  # Navigate to Laravel app directory
        php artisan test
